### ISSUE TITLE
urllib2- or requests-compatible wrapper for app engine's async urlfetch

### ISSUE THREAD

**Issue by snarfed** [snarfed/webutil#3]
[app engine's async urlfetch feature](https://cloud.google.com/appengine/docs/python/urlfetch/asynchronousrequests) is useful, but awkward to use in established codebases that already have existing code paths using urllib2 or [requests](https://github.com/kennethreitz/requests).

one solution would be to write a wrapper that reproduces urllib2's or requests's API, or at least a minimal subset, and passes through to async urlfetch underneath. it would fire off the initial RPC when called, immediately return, and only block on the result when the caller tries to `read()` the response, access response headers, etc.

this would help snarfed/bridgy#578, snarfed/bridgy#603, snarfed/bridgy#624, etc. converting even small parts of bridgy to async urlfetch would be pretty invasive otherwise.

i'm filing this issue here because it _could_ be part of webutil, but ideally it should probably be its own pypi package.

cc @kylewm in case you're interested in a small but complex/deep project!

**Comment by snarfed** [comment]
this would also make it easy to make libraries use async urlfetch even if they don't depend on/aren't aware of app engine at all, e.g. granary. :P

**Comment by snarfed** [comment]
btw, i figured someone must have done this already, and i searched high and low, but no luck. i'd happily use anything that does exist though!

**Comment by karadaisy** [comment]
I like the idea of a wrapper that granary can use to not be dependent on appengine.

My gut reaction is that it should not follow requests or urllib2 too closely, should present an interface specific to async requests instead. Like instead of returning a Response, it should return a Future/Promise. The code is going to have to be rearranged pretty significantly already, and we have to deal with async requests in a very specific way, and I worry making it look to much like a sync API will make that confusing.

**Comment by snarfed** [comment]
huh. thanks for the feedback!

my motivation was a bit different. i was explicitly thinking of being compatible with urllib2/requests so we could make some parts of the existing code async as is, without invasive changes.

you're right though, there are definitely drawbacks to that. meh.

**Comment by snarfed** [comment]
the new python 3 app engine runtime drops all of the proprietary APIs like urlfetch entirely, so this is now obsolete.
